### ISSUE TITLE
starter

### ISSUE THREAD

**Issue by LiTiang** [thrandre/ava-webpack#1]
like _angular2-webpack-starter_

could  u please give a example how to use _AVA_ with _Webpack_?

**Comment by thrandre** [comment]
Sorry, but I have been extremely busy lately. I have added a minimal usage example, but the implementation and readme both need a bit of polishing. I am available for questions, but I hope this is enough to get you started.

Thank you!

**Comment by LiTiang** [comment]
@thrandre, i very very appreciate u reply me

& i also appreciate u present an example, 

now i just have one more question about the functions of ava-webpack.

---

In github project naming "angular2-webpack-starter",

i find out **Karma** do a magic thing,

when we run unit testing on typescript file, 

**Karma** will use  **webpack** to transpile typescript, 

then **Karma** will test the result which **webpack** given !!!

( javascript file in memory, because we actually dont see any javascript file after transpiling by **webapck**)

but i dont want to use **Karma** for some reason,

"angular2-webpack-starter" use **karma-webpack**, 

so it can do the magic i stated above.

so ... does **ava-webpack** also have the function i want ?

**Comment by thrandre** [comment]
No worries!

Firstly - You need to be aware that the inner workings of AVA and Karma are quite different. AVA runs your tests in Node while Karma require a browser (PhantomJS is often used for headless testing). Transpiling works pretty much the same in both cases, but keep in mind that webpack was initially created as a module bundler for the browser. Karma - being a more mature test runner - has better support for preprocessing than AVA currently has.

As for how `ava-webpack` work:
- Tests matching the glob you provide will be added as entries for webpack.
- Webpack transpiles your tests with the loaders provided in your config.
- Transpiled tests are emitted to a folder named `.ava-webpack`.
- The transpiled tests are fed to `ava`

Keep in mind that there is absolutely no sophistication behind this. This project is intended as a hackish solution to get `AVA` working with `TypeScript` (`AllowSyntheticImports` enabled). It is also worth mentioning that this project is temporary - waiting for `AVA` to implement planned support for `webpack` and `browserify` (https://github.com/avajs/ava/issues/24).

If you are determined to run your tests in Node, but not necessarily with the use of AVA, you should consider Mocha and `mocha-webpack` (https://github.com/zinserjan/mocha-webpack) instead. 

To answer your question: Yes, `ava-webpack` will perform the magic you describe, but maybe not in the way you want.

**Comment by LiTiang** [comment]
@thrandre 
thanks a lot, i will try it
then i will let u know if i success or not
thanks again

**Comment by LiTiang** [comment]
Hi, @thrandre 

i still fail to integrate **ava-webpack** with "angular2-webpack-starter", 
may be such thing is too difficult for me ... 
anyway, thanks u contribution.
