### ISSUE TITLE
Windows Line Endings Break Shabang

### ISSUE THREAD

**Issue by Jwashton** [thrandre/ava-webpack#4]
When I try to run ava-webpack after a fresh npm (actually yarn, but that shouldn't matter here) install, I get this error:

```
/usr/bin/env: ‘node\r’: No such file or directory
```

This goes away when I remove the windows line endings from `cli.js`. (For me that means opening the file in vim and running `:set ff=unix`.) After that things seem to work fine.

I'm running Fedora Linux & Node 7.0.0

**Comment by Jwashton** [comment]
Well, I thought this would be a quick fix but git itself is actually getting in my way here. After I forked the repo, I can confirm that the problem exists by pointing yarn to the forked version. However, when I clone the fork git applies some special sauce and says "since you're running Linux you really don't want those `\r`s in your project do you?". Therefor, I see no `\r` to remove.

**Comment by joeyfigaro** [comment]
This is affecting OS X as well: 
`env: node\r: No such file or directory`

**Comment by joeyfigaro** [comment]
Looks like converting the line endings to unix still doesn't fix the issue. @thrandre

**Comment by thrandre** [comment]
I can confirm that the files in the npm package had CRLF-endings. I have corrected this and published a new package to npm with the patch. Can any of you help me confirm if this is working or not? I'm on Windows for the time being. If this still doesn't work I will investigate further, @joeyfigaro.
